version: "2.2"
services:
  ######################################## Traefik ########################################
  traefik:
    build: 
      context: .
      dockerfile: docker/traefik/Dockerfile-v2-traefik
    container_name: "traefik"
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.hackinglab.local`)"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  ######################################## whomai ########################################
  whoami:
    image: "containous/whoami"
    container_name: "traefik-whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.hackinglab.local`)"
      - "traefik.http.routers.whoami.tls=true"