version: "3.3"
services: 
  traefik:
    image: traefik:v1.7-alpine
    restart: unless-stopped
    configs: 
      - source: traefik-toml-conf
        target: /etc/traefik/traefik.toml
    secrets:
      - traefik-ssl-key
      - traefik-ssl-crt
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:80
      - 8001:8080
      - 8443:443
  whoami:
    image: "containous/whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

configs:
  traefik-toml-conf:
    external: true

secrets:
  traefik-ssl-key:
    external: true
  traefik-ssl-crt:
    external: true