version: "3.3"
services:
  ######################################## Traefik ########################################
  traefik:
    image: traefik:v2.2
    container_name: "traefik"
    restart: unless-stopped
    configs: 
      - source: traefik-conf
        target: /etc/traefik/traefik.yml
      - source: traefik-dyn
        target: /etc/traefik/dyn.yml
    secrets:
      - traefik-ssl-key
      - traefik-ssl-crt
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.hackinglab.local`)"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
  ######################################## whomai ########################################
  whoami:
    image: "containous/whoami"
    container_name: "traefik-whoami"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.hackinglab.local`)"
      - "traefik.http.routers.whoami.tls=true"

configs:
  traefik-conf:
    external: true
  traefik-dyn:
    external: true
  

secrets:
  traefik-ssl-key:
    external: true
  traefik-ssl-crt:
    external: true
