version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - backcend
    secrets:
      - ssl-pub-key
      - ssl-priv-key
  

networks:
  backcend:

volumes:


configs:
  nginx-main-config:

secrets:
  ssl-pub-key:
  ssl-priv-key: